In [3]:
import ginsim
import boolsim
import bns
import os
from colomoto import minibn
import biolqm
from colomoto_jupyter import tabulate
import csv
import pandas as pd
import numpy as np
import time

This notebook has been executed using the docker image `colomoto/colomoto-docker:2023-10-01`

In [4]:
current_path=os.getcwd()

## The Cardiomyocyte BN

In [10]:
model = minibn.BooleanNetwork.load("CardiomyocyteBN.bnet")
model
lqm2 = biolqm.load("CardiomyocyteBN.bnet")
lrg = biolqm.to_ginsim(lqm2)
ginsim.show(lrg)
# Asynchronous Attractors
a = boolsim.attractors(model.to_biolqm())
tabulate(a)

   GATA46  HAND2  HEY2  IRX4  MYL2  MYL7  NOTCH  NR2F2  RA
0       1      1     0     0     0     1      1      1   1
1       1      1     1     1     1     0      1      0   0

In [11]:
ginsim.show(lrg)

## The Heart Fielf BN by Hermann et al.

In [12]:
model = minibn.BooleanNetwork.load("HeartFieldBN_Hermann.bnet")
model
lqm2 = biolqm.load("HeartFieldBN_Hermann.bnet")
lrg = biolqm.to_ginsim(lqm2)
ginsim.show(lrg)
# Asynchronous Attractors
a = boolsim.attractors(model.to_biolqm())
tabulate(a)

,BMP2,DKK1,ex_BMP2,ex_WNT,FGF8,FOXC12,GATA46,ISL1,MESP1,NKX25,TBX1,TBX5,WNT
0,0,0,1,1,1,1,1,1,0,1,1,0,1
2,1,0,1,0,0,0,0,0,0,0,0,0,0
1,1,0,1,0,0,0,1,0,0,1,0,1,0

In [13]:
ginsim.show(lrg)

## The unified BN

In [6]:
model = minibn.BooleanNetwork.load("Unified.bnet")
model
lqm2 = biolqm.load("Unified.bnet")
lrg = biolqm.to_ginsim(lqm2)
ginsim.show(lrg)
# Asynchronous Attractors
a = boolsim.attractors(model.to_biolqm())
tabulate(a)

,BMP2,DKK1,ex_BMP2,ex_WNT,FGF8,FOXC12,GATA46,HAND2,HEY2,IRX4,ISL1,MESP1,MYL2,MYL7,NKX25,NOTCH,NR2F2,RA,TBX1,TBX5,WNT
5,0,0,1,1,1,1,1,1,0,0,1,0,0,1,1,1,1,1,1,0,1
1,0,0,1,1,1,1,1,1,1,1,1,0,1,0,1,1,0,0,1,0,1
4,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
3,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,0,0
0,1,0,1,0,0,0,1,1,0,0,0,0,0,1,1,1,1,1,0,1,0
2,1,0,1,0,0,0,1,1,1,1,0,0,1,0,1,1,0,0,0,1,0

In [7]:
ginsim.show(lrg)

In [8]:
#attractors_model = bns.attractors(model.to_biolqm())
#tabulate(attractors_model)
#f = open("attractors.csv", "a")
#for attractor in attractors_model:
#    f.write(str(attractor)+",\n")
#f.close()